"""Constants used by SolarEdge Modbus Multi components."""

from __future__ import annotations

import re
from enum import IntEnum, StrEnum
from typing import Final

DOMAIN = "solaredge_modbus_multi"
DEFAULT_NAME = "SolarEdge"

# raise a startup exception if pymodbus version is less than this
PYMODBUS_REQUIRED_VERSION = "3.8.3"

# units missing in homeassistant core
ENERGY_VOLT_AMPERE_HOUR: Final = "VAh"
ENERGY_VOLT_AMPERE_REACTIVE_HOUR: Final = "varh"

# from voluptuous/validators.py
DOMAIN_REGEX = re.compile(
    # start anchor, because fullmatch is not available in python 2.7
    "(?:"
    # domain
    r"(?:[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?\.)+"
    r"(?:[A-Z]{2,6}\.?|[A-Z0-9-]{2,}\.?$)"
    # host name only
    r"|(?:^[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?)"
    # end anchor, because fullmatch is not available in python 2.7
    r")\Z",
    re.IGNORECASE,
)

DETECT_EVSE_REGEX = re.compile(
    r"^(?:SE-EV-SA)",  # Add additional prefixes with |OTHER-PREFIX
    re.IGNORECASE,
)

STATUS_VENDOR4_VERSION = "3.20.0"


class ModbusExceptions:
    """An enumeration of the valid modbus exceptions."""

    """
        Copied from pymodbus source:
        https://github.com/pymodbus-dev/pymodbus/blob/a1c14c7a8fbea52618ba1cbc9933c1dd24c3339d/pymodbus/pdu/pdu.py#L72
    """

    IllegalFunction = 0x01
    IllegalAddress = 0x02
    IllegalValue = 0x03
    DeviceFailure = 0x04
    Acknowledge = 0x05
    DeviceBusy = 0x06
    NegativeAcknowledge = 0x07
    MemoryParityError = 0x08
    GatewayPathUnavailable = 0x0A
    GatewayNoResponse = 0x0B


class RetrySettings(IntEnum):
    """Retry settings when opening a connection to the inverter fails."""

    Time = 800  # first attempt in milliseconds
    Ratio = 3  # time multiplier between each attempt
    Limit = 5  # number of attempts before failing


class ModbusDefaults(IntEnum):
    """Values to pass to pymodbus"""

    """
        ReconnectDelay doubles automatically with each unsuccessful connect, from
        ReconnectDelay to ReconnectDelayMax.
        Set `ReconnectDelay = 0` to avoid automatic reconnection.
        Disabled because it didn't work properly with HA Async in PR#360.

        ReconnectDelay and ReconnectDelayMax can be set to seconds.milliseconds
        values using the advanced YAML configuration option.
    """

    Timeout = 3  # Timeout for a request, in seconds.
    Retries = 3  # Max number of retries per request.
    ReconnectDelay = 0  # Minimum in seconds before reconnecting.
    ReconnectDelayMax = 3  # Maximum in seconds before reconnecting.


class SolarEdgeTimeouts(IntEnum):
    """Timeouts in milliseconds."""

    Inverter = 8400
    Device = 1200
    Init = 1200
    Read = 6000


class BatteryLimit(IntEnum):
    """Configure battery limits for input and display validation."""

    Vmin = 0  # volts
    Vmax = 1000  # volts
    Amin = -200  # amps
    Amax = 200  # amps
    Tmax = 100  # degrees C
    Tmin = -30  # degrees C
    ChargeMax = 1000000  # watts
    DischargeMax = 1000000  # watts


class ConfDefaultInt(IntEnum):
    """Defaults for options that are integers."""

    SCAN_INTERVAL = 300
    PORT = 1502
    SLEEP_AFTER_WRITE = 0
    BATTERY_RATING_ADJUST = 0
    BATTERY_ENERGY_RESET_CYCLES = 0


class ConfDefaultFlag(IntEnum):
    """Defaults for options that are booleans."""

    DETECT_METERS = 1
    DETECT_BATTERIES = 0
    DETECT_EXTRAS = 0
    KEEP_MODBUS_OPEN = 0
    ADV_PWR_CONTROL = 0
    ADV_STORAGE_CONTROL = 0
    ADV_SITE_LIMIT_CONTROL = 0
    ALLOW_BATTERY_ENERGY_RESET = 0


class ConfDefaultStr(StrEnum):
    """Defaults for options that are strings."""

    DEVICE_LIST = "1"


class ConfName(StrEnum):
    DEVICE_LIST = "device_list"
    DETECT_METERS = "detect_meters"
    DETECT_BATTERIES = "detect_batteries"
    DETECT_EXTRAS = "detect_extras"
    KEEP_MODBUS_OPEN = "keep_modbus_open"
    ADV_PWR_CONTROL = "advanced_power_control"
    ADV_STORAGE_CONTROL = "adv_storage_control"
    ADV_SITE_LIMIT_CONTROL = "adv_site_limit_control"
    ALLOW_BATTERY_ENERGY_RESET = "allow_battery_energy_reset"
    SLEEP_AFTER_WRITE = "sleep_after_write"
    BATTERY_RATING_ADJUST = "battery_rating_adjust"
    BATTERY_ENERGY_RESET_CYCLES = "battery_energy_reset_cycles"

    # Old config entry names for migration
    NUMBER_INVERTERS = "number_of_inverters"
    DEVICE_ID = "device_id"


class SunSpecAccum(IntEnum):
    NA16 = 0x0000
    NA32 = 0x00000000
    LIMIT16 = 0xFFFF
    LIMIT32 = 0xFFFFFFFF


class SunSpecNotImpl(IntEnum):
    INT16 = 0x8000
    UINT16 = 0xFFFF
    INT32 = 0x80000000
    UINT32 = 0xFFFFFFFF
    FLOAT32 = 0x7FC00000


# Battery ID and modbus starting address
BATTERY_REG_BASE = {
    1: 57600,
    2: 57856,
    3: 58368,
}

# Meter ID and modbus starting address
METER_REG_BASE = {
    1: 40121,
    2: 40295,
    3: 40469,
}

SUNSPEC_SF_RANGE = [
    -10,
    -9,
    -8,
    -7,
    -6,
    -5,
    -4,
    -3,
    -2,
    -1,
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
]

# parameter names per sunspec
DEVICE_STATUS = {
    1: "I_STATUS_OFF",
    2: "I_STATUS_SLEEPING",
    3: "I_STATUS_STARTING",
    4: "I_STATUS_MPPT",
    5: "I_STATUS_THROTTLED",
    6: "I_STATUS_SHUTTING_DOWN",
    7: "I_STATUS_FAULT",
    8: "I_STATUS_STANDBY",
}

# English descriptions of parameter names
DEVICE_STATUS_TEXT = {
    1: "Off",
    2: "Sleeping (Auto-Shutdown)",
    3: "Grid Monitoring",
    4: "Production",
    5: "Production (Curtailed)",
    6: "Shutting Down",
    7: "Fault",
    8: "Maintenance",
}

VENDOR_STATUS = {
    SunSpecNotImpl.INT16: None,
    0: "No Error",
    17: "Temperature Too High",
    25: "Isolation Faults",
    27: "Hardware Error",
    31: "AC Voltage Too High",
    33: "AC Voltage Too High",
    32: "AC Voltage Too Low",
    34: "AC Frequency Too High",
    35: "AC Frequency Too Low",
    41: "AC Voltage Too Low",
    44: "No Country Selected",
    61: "AC Voltage Too Low",
    62: "AC Voltage Too Low",
    63: "AC Voltage Too Low",
    64: "AC Voltage Too High",
    65: "AC Voltage Too High",
    66: "AC Voltage Too High",
    67: "AC Voltage Too Low",
    68: "AC Voltage Too Low",
    69: "AC Voltage Too Low",
    79: "AC Frequency Too High",
    80: "AC Frequency Too High",
    81: "AC Frequency Too High",
    82: "AC Frequency Too Low",
    83: "AC Frequency Too Low",
    84: "AC Frequency Too Low",
    95: "Hardware Error",
    97: "Vin Buck Max",
    104: "Temperature Too High",
    106: "Hardware Error",
    107: "Battery Communication Error",
    110: "Meter Communication Error",
    120: "Hardware Error",
    121: "Isolation Faults",
    125: "Hardware Error",
    126: "Hardware Error",
    150: "Arc Fault Detected",
    151: "Arc Fault Detected",
    153: "Hardware Error",
    191: "Swing Rcommon Overheat",
    256: "Arc Detected",
}

SUNSPEC_DID = {
    101: "Single Phase Inverter",
    102: "Split Phase Inverter",
    103: "Three Phase Inverter",
    160: "Multiple MPPT Inverter Extension",
    201: "Single Phase Meter",
    202: "Split Phase Meter",
    203: "Three Phase Wye Meter",
    204: "Three Phase Delta Meter",
}

METER_EVENTS = {
    2: "POWER_FAILURE",
    3: "UNDER_VOLTAGE",
    4: "LOW_PF",
    5: "OVER_CURRENT",
    6: "OVER_VOLTAGE",
    7: "MISSING_SENSOR",
    8: "RESERVED1",
    9: "RESERVED2",
    10: "RESERVED3",
    11: "RESERVED4",
    12: "RESERVED5",
    13: "RESERVED6",
    14: "RESERVED7",
    15: "RESERVED8",
    16: "OEM1",
    17: "OEM2",
    18: "OEM3",
    19: "OEM4",
    20: "OEM5",
    21: "OEM6",
    22: "OEM7",
    23: "OEM8",
    24: "OEM9",
    25: "OEM10",
    26: "OEM11",
    27: "OEM12",
    28: "OEM13",
    29: "OEM14",
    30: "OEM15",
}

BATTERY_STATUS = {
    0: "B_STATUS_OFF",
    1: "B_STATUS_STANDBY",
    2: "B_STATUS_INIT",
    3: "B_STATUS_CHARGE",
    4: "B_STATUS_DISCHARGE",
    5: "B_STATUS_FAULT",
    6: "B_STATUS_PRESERVE_CHARGE",
    7: "B_STATUS_IDLE",
    10: "B_STATUS_POWER_SAVING",
}

BATTERY_STATUS_TEXT = {
    0: "Off",
    1: "Standby",
    2: "Initializing",
    3: "Charge",
    4: "Discharge",
    5: "Fault",
    6: "Preserve Charge",
    7: "Idle",
    10: "Power Saving",
}

RRCR_STATUS = {
    3: "L1",
    2: "L2",
    1: "L3",
    0: "L4",
}

MMPPT_EVENTS = {
    0: "GROUND_FAULT",
    1: "INPUT_OVER_VOLTAGE",
    3: "DC_DISCONNECT",
    5: "CABINET_OPEN",
    6: "MANUAL_SHUTDOWN",
    7: "OVER_TEMP",
    12: "BLOWN_FUSE",
    13: "UNDER_TEMP",
    14: "MEMORY_LOSS",
    15: "ARC_DETECTION",
    19: "RESERVED",
    20: "TEST_FAILED",
    21: "INPUT_UNDER_VOLTAGE",
    22: "INPUT_OVER_CURRENT",
}

REACTIVE_POWER_CONFIG = {
    0: "Fixed CosPhi",
    1: "Fixed Q",
    2: "CosPhi(P)",
    3: "Q(U) + Q(P)",
    4: "RRCR",
}

STORAGE_CONTROL_MODE = {
    0: "Disabled",
    1: "Maximize Self Consumption",
    2: "Time of Use",
    3: "Backup Only",
    4: "Remote Control",
}

STORAGE_AC_CHARGE_POLICY = {
    0: "Disabled",
    1: "Always Allowed",
    2: "Fixed Energy Limit",
    3: "Percent of Production",
}

STORAGE_MODE = {
    0: "Solar Power Only (Off)",
    1: "Charge from Clipped Solar Power",
    2: "Charge from Solar Power",
    3: "Charge from Solar Power and Grid",
    4: "Discharge to Maximize Export",
    5: "Discharge to Minimize Import",
    7: "Maximize Self Consumption",
}

LIMIT_CONTROL_MODE = {
    None: "Disabled",
    0: "Export Control (Export/Import Meter)",
    1: "Export Control (Consumption Meter)",
    2: "Production Control",
}

LIMIT_CONTROL = {0: "Total", 1: "Per Phase"}

VENDOR4_STATUS: dict[int, dict[int, str]] = {
    0x3: {
        0x0: "Reset",
        0x1: "Set Real Time Clock",
        0x2: "Inverter Communication Error",
        0x3: "RRCR State Changed",
        0x4: "RRCR Illegal State",
        0x5: "Remote Shutdown State Changed",
        0x6: "Software Upgrade",
        0x7: "Pairing",
        0x8: "Activation",
        0x9: "Modbus Meter Error",
        0xA: "Phase Imbalance",
        0xB: "No Country Selected",
        0xC: "Software Error",
        0xD: "Phase Imbalance",
        0xE: "Maximum Vdc not Selected",
        0xF: "Software Error",
        0x10: "No SD Card Detected",
        0x11: "Arc Detected",
        0x12: "For info contact your installer",
        0x13: "Remote Shutdown timeout",
        0x14: "Internal Revenue Grade Meter Error",
        0x15: "Meter Communication Error",
        0x16: "Battery Communication Error",
        0x17: "Battery Internal Error",
        0x18: "Lock on trip",
        0x19: "Lock Rapid Shutdown test",
        0x1A: "String Overvoltage",
        0x1B: "Battery Force Sleep",
        0x1C: "Battery without firmware",
        0x1E: "Phase Balancer",
        0x1F: "EVSE communication error",
        0x20: "L1 CT Disconnected",
        0x21: "L2 CT Disconnected",
        0x22: "L3 CT Disconnected",
        0x23: "CTs disconnected",
        0x24: "L1 Phase Disconnected",
        0x25: "L2 Phase Disconnected",
        0x26: "L3 Phase Disconnected",
        0x27: "Phases Disconnected",
        0x28: "Battery Internal Fault",
        0x29: "Pairing failed",
        0x64: "FIFO Reset",
        0x65: "RRCR State Changed",
        0x66: "ID Change/Reset",
        0x67: "Energy Manager Log",
        0x68: "Energy Statistics Log",
        0x69: "Bus Event",
        0x6A: "System Lock",
        0x6B: "Battery Communication Error",
        0x6C: "Battery Internal Error",
        0x6D: "Revenue Grade Meter CT Error",
        0x6E: "Meter Communication Error",
        0x6F: "Meter Internal Error",
        0x70: "Stack Usage Warning",
        0x71: "Storage Manager Log",
        0x72: "Daily TCP Report",
        0x73: "Log Prints Dump",
        0x74: "General Debug",
        0x75: "Daily RSSI Report",
        0x76: "Manager Reset",
        0x77: "Storage Mode Change",
        0x78: "Load Device State Change",
        0x79: "S_OK (debug)",
        0x7A: "Optimizer Detect",
        0x7B: "String Detect",
        0x7C: "Battery Upgrade",
        0x7D: "Modbus Request",
        0x7E: "Battery Wrong State",
        0x7F: "Packet Log",
        0x80: "Battery Force Sleep",
        0x81: "Load Device User Intervened",
        0x82: "Battery without firmware",
        0x83: "Phase Balancer",
        0x84: "Bad Energy Delta",
        0x85: "EVSE Comm. Error",
        0x86: "Storage Internal Control",
        0x87: "New Battery Detect",
        0x88: "Meter CT Loss Error",
        0x89: "Inv. Unit Comm. Error",
        0x8A: "Meter Phase Loss Error",
        0x8B: "DSP Auto Detect",
        0x8C: "Battery Self Test Start",
        0x8D: "Battery Self Test End",
        0x8E: "Battery Min SOE Alarm",
        0x8F: "Manager Pairing Failed",
        0x90: "TCP Comm. Error",
        0x91: "System Lock Unlocked",
        0x92: "System Lock Fire Safety",
        0x93: "System Lock Standby Mode",
        0x94: "For info contact your installer",
        0x95: "For info contact your installer",
        0x96: "System Lock Temporary",
        0x97: "System Lock AC Relay Control",
        0x98: "System Lock Diesel Generator",
        0x99: "Lock on Trip, OFF/ON to Reconnect",
        0x9A: "System Lock Inverter ARC Detected",
        0x9B: "RSD Test Failed, OFF/ON to Reconnect",
        0x9C: "System Lock Inverter After Min Cap",
        0x9D: "System Lock Inverter After Pre RSD Test",
        0x9E: "Inverter locked due to offgrid over consumption. Push switch to OFF and then ON to unlock.",
        0x9F: "Critical Data Restored",
        0xA0: "Critical Data Stored",
        0xA1: "Critical Data Not Found",
        0xA2: "Grid Services Event Start",
        0xA3: "DC DC internal event",
        0xA4: "UART stats",
        0xA5: "Modbus routing packets debug",
        0xA6: "Modbus duplicate ID",
        0xA7: "Country Mismatch",
        0xA8: "Enter Recovery Mode",
        0xA9: "Recovery Mode Auto Detect",
        0xAA: "Exit Recovery Mode",
        0xB5: "Meter - L1 CT is disconnected",
        0xB6: "Meter - L2 CT is disconnected",
        0xB7: "Meter - L3 CT is disconnected",
        0xB8: "Meter - Multiple CTs are disconnected",
        0xB9: "Meter - L1 phase Voltage is disconnected",
        0xBA: "Meter - L2 phase Voltage is disconnected",
        0xBB: "Meter - L3 phase Voltage is disconnected",
        0xBC: "Meter - Multiple phase Voltages are disconnected",
        0xBD: "Backup Interface communication error",
        0xBE: "Arc detection lock",
        0xBF: "Battery wake-up",
        0xC0: "Xbee Tx status",
        0xC1: "Export kill switch",
        0xC2: "GSM SMS activation",
        0xC3: "WN errors stats",
        0xC4: "Sys Event Sys Monitor",
        0xC5: "Cb protection conf changed",
        0xC6: "Cb protection over-current detected",
        0xC7: "Cb protection EVSE communication error",
        0xC8: "Cb protection EVSE communication restored",
        0xC9: "Cb protection reference changed",
        0xCA: "Monitoring Event Monitoring Details",
        0xCB: "Cell Event Cell Debug",
        0xCC: "Position fault",
        0xCD: "DSP3 communication",
        0xCE: "WN stats2",
        0xCF: "Locations detected",
        0xE9: "Unsupported LG battery type detected",
        0xF4: "Inverter Communication Error",
        0x100: "SunSpec enter service lock",
        0x10D: "Smart Device communication",
        0x10E: "Sense Connect Inverter Lock on Power Optimizer",
        0x114: "Lock due to Generator on",
        0x116: "SolarEdge LV Battery Module Mismatch",
        0x11E: "Inverter is locked, please contact SolarEdge support",
        0x11F: "Inverter is locked, please contact SolarEdge support",
        0x125: "Inverter is locked due to a HW failure (Desat), please contact SolarEdge support",
        0x128: "Meter is in read only mode. Set meter communication protection to 'Disable'",
        0x136: "Follower Inverter communication error",
        0x138: "Your Network Service Provider has de-energized this system by remote command",
        0x139: "BCM Activated",
        0x13A: "BCM Configuration Updated",
        0x13B: "BCM Fallback Mode",
        0x13C: "BCM Operational Abnormality",
        0x13E: "CT Calibration Ended",
        0x13F: "BCM Startup BIT Ended",
        0x140: "CT Loss Detected",
        0x162: "CT Loss - short circuit on L1",
        0x163: "CT Loss - short circuit on L2",
        0x164: "CT Loss - short circuit on L3",
        0x165: "CT Loss - open circuit on L1",
        0x166: "CT Loss - open circuit on L2",
        0x167: "CT Loss - open circuit on L3",
    },
    0x8: {
        0x0: "No Event",
        0x1: "Wakeup",
        0x2: "User Turn off",
        0x3: "Night Mode",
        0x4: "System Reset",
        0x5: "Test Mode",
        0x6: "Relay",
        0x7: "Country Slec",
        0x8: "Switched",
        0x9: "External Reset",
        0xA: "Step Out Night Mode",
        0xB: "VAC unstable (THD fast changes)",
        0xC: "ARC_DETECTED",
        0xD: "ARC_POWER_DETECT",
        0xE: "RX_TX_STARTUP_TEST",
        0xF: "ARC_DETECT_DEBUG",
        0x10: "Communication",
        0x11: "Unexpected Mode",
        0x12: "Supervise",
        0x13: "Vin Decrease Timeout",
        0x14: "Unknown error",
        0x15: "JM Sync Timeout",
        0x16: "Main Capacitor estimation event",
        0x17: "Main Capacitor error",
        0x18: "RSD error",
        0x19: "V-L1 Max1",
        0x1A: "V-L2 Max1",
        0x1B: "V-L3Max1",
        0x1C: "V-L1 Min1",
        0x1D: "V-L2 Min1",
        0x1E: "V-L3 Min1",
        0x1F: "V-L1 Max2",
        0x20: "V-L2 Max2",
        0x21: "V-L3 Max2",
        0x22: "V-L1 Min2",
        0x23: "V-L2 Min2",
        0x24: "V-L3 Min2",
        0x25: "V-Line Max",
        0x26: "V-Line Min",
        0x27: "I-ACDC L1",
        0x28: "Unknown",
        0x29: "I-ACDC L2",
        0x2A: "I-ACDC L3",
        0x2B: "I-RCD 1",
        0x2C: "I-RCD 2",
        0x2D: "JP Sync Timeout",
        0x2E: "F-L1 Max",
        0x2F: "F-L2 Max",
        0x30: "F-L3 Max",
        0x31: "F-L1 Min",
        0x32: "F-L2 Min",
        0x33: "F-L3 Min",
        0x34: "VinP Max",
        0x35: "VinM Max",
        0x36: "Active anti-islanding",
        0x37: "Vin Max",
        0x38: "Passive anti-islanding",
        0x39: "TZ RCD",
        0x3A: "TZ L1",
        0x3B: "TZ L2",
        0x3C: "TZ L3",
        0x3D: "TZ ITO",
        0x3E: "TZ Misc",
        0x3F: "Iac L1 Max",
        0x40: "Iac L2 Max",
        0x41: "Iac L3 Max",
        0x42: "Vsrg L1 Max (Vac/Vfilter voltage spike)",
        0x43: "Vsrg L2 Max (Vac/Vfilter voltage spike)",
        0x44: "Vsrg L3 Max (Vac/Vfilter voltage spike)",
        0x45: "Vdc Plus Max (Vdc+ voltage spike)",
        0x46: "Vdc Minus Max (Vdc- voltage spike)",
        0x47: "Over temperature",
        0x48: "Under temperature",
        0x49: "Reference voltage",
        0x4A: "WD Reset",
        0x4B: "ISR Timing 1",
        0x4C: "ISR Timing 2",
        0x4D: "WR State Ref",
        0x4E: "WR State State",
        0x4F: "Wrong AC connection",
        0x50: "Main State State",
        0x51: "IRCD surge (IRCD spike)",
        0x52: "VDC+/- capacitors banks unbalanced",
        0x53: "VNN error",
        0x54: "Low power",
        0x55: "Grid monitoring",
        0x56: "Power train error",
        0x57: "Temperature Sensor",
        0x58: "Isolation",
        0x59: "Relay Test",
        0x5A: "Offset Gain",
        0x5B: "RCD Test",
        0x5C: "Switch",
        0x5D: "Test Isolation Test",
        0x5E: "RsrvdInit1",
        0x5F: "RsrvdInit2",
        0x60: "RsrvdInit3",
        0x61: "RsrvdInit4",
        0x62: "Fan 1 OK",
        0x63: "Fan 2 OK",
        0x64: "Fan 3 OK",
        0x65: "Fan 4 OK",
        0x66: "Fan 1 Dying",
        0x67: "Fan 2 Dying",
        0x68: "Fan 3 Dying",
        0x69: "Fan 4 Dying",
        0x6A: "Fan 1 Not working",
        0x6B: "Fan 2 Not working",
        0x6C: "Fan 3 Not working",
        0x6D: "Fan 4 Not working",
        0x6E: "Fan Controller 12 Error",
        0x6F: "Fan Controller 34 Error",
        0x70: "Fan Controller 3 Error",
        0x71: "Fan 5 OK",
        0x72: "Fan 6 OK",
        0x73: "Fan 5 Not working",
        0x74: "Fan 6 Not working",
        0x75: "Bank+ Over Voltage",
        0x76: "Bank- Over Voltage",
        0x77: "L1-Over Temperature",
        0x78: "L2-Over Temperature",
        0x79: "L3-Over Temperature",
        0x7A: "L1-Over Current",
        0x7B: "L2-Over Current",
        0x7C: "L3-Over Current",
        0x7D: "L1-Driver Short",
        0x7E: "L2-Driver Short",
        0x7F: "L3-Driver Short",
        0x80: "Balancer Fault",
        0x81: "RCD Over Current",
        0x82: "NC",
        0x83: "Global Fault",
        0x84: "ARC_POWER_LIMIT",
        0x85: "SPD AC",
        0x86: "SPD DC",
        0x87: "F-L1 Max6To10",
        0x88: "F-L2 Max6To10",
        0x89: "F-L3 Max6To10",
        0x8A: "F-L1 Min6To10",
        0x8B: "F-L2 Min6To10",
        0x8C: "F-L3 Min6To10",
        0x8D: "V-L1 Max6To10",
        0x8E: "V-L2 Max6To10",
        0x8F: "V-L3 Max6To10",
        0x90: "V-L1 Min6To10",
        0x91: "V-L2 Min6To10",
        0x92: "V-L3 Min6To10",
        0x93: "V-Line Max2To10",
        0x94: "V-Line Min2To10",
        0x95: "UART Break",
        0x96: "VL2L Surge",
        0x97: "Vdc Neg. Grad. Surge",
        0xA5: "Multiple seq. GB",
        0xB5: "GB Event",
        0xB6: "Stand alone pairing error",
        0xB7: "Manager startup error",
        0xB8: "Pairing error",
        0xB9: "Locked",
        0xBA: "Arc detected",
        0xBB: "Ycap estimation",
        0xBC: "Vdc balance iso test",
        0xBD: "Vdc balancing",
        0xBE: "Internal error",
        0xBF: "Internal error",
        0xC0: "Cannot detect grid",
        0xC1: "Internal error",
        0xC2: "AC cycle the inverter",
        0xC3: "AC cycle the inverter",
        0xC4: "AC cycle the inverter",
        0xC5: "ArcHs exception",
        0xC6: "AC cycle the inverter",
        0xC7: "AC cycle the inverter",
        0xC8: "AC cycle the inverter",
        0xC9: "AC cycle the inverter",
        0xCA: "Validate that SPDs are connected",
        0xCB: "AC cycle the inverter",
        0xCC: "AC cycle the inverter",
        0xCD: "AC cycle the inverter",
        0xCE: "AC cycle the inverter",
        0xCF: "AC cycle the inverter",
        0xD0: "AC cycle the inverter",
        0xD1: "DSP3 trip zone error",
        0xD2: "DSP3 event #:",
        0xD3: "DSP3 communication error",
        0xD4: "Vf ESR Timeout",
        0xE1: "Sense Connect Event on Power Optimizer",
        0xE2: "Sense Connect Inverter Lock on Power Optimizer",
        0xE3: "FPGA communication",
        0xE4: "FPGA communication OK",
        0xE5: "EEPROM read",
        0xE6: "Sense Connect temperature exceeds range",
    },
    0x18: {
        0x0: "No Event",
        0x1: "Wakeup",
        0x2: "User Turn-off",
        0x3: "Night Mode",
        0x4: "System Reset",
        0x5: "Test Mode",
        0x6: "Relay",
        0x7: "Country Selected",
        0x8: "Switched",
        0x9: "External Reset",
        0xA: "Step Out Night Mode",
        0xB: "Vac Unstable",
        0xC: "ARC Detected",
        0xD: "ARC Power Detect",
        0xE: "RX TX Startup Test",
        0xF: "ARC Detect Debug",
        0x10: "Communication",
        0x11: "Unexpected Mode",
        0x12: "Supervise",
        0x13: "Vin Decrease Timeout",
        0x14: "Inv. Power Error - No Code",
        0x15: "Sync Timeout",
        0x16: "Main Cap Est",
        0x17: "Main Cap error",
        0x18: "Power Boot Error",
        0x19: "V-L1 Max1",
        0x1A: "V-L2 Max1",
        0x1B: "V-L3 Max1",
        0x1C: "V-L1 Min1",
        0x1D: "V-L2 Min1",
        0x1E: "V-L3 Min1",
        0x1F: "V-L1 Max2",
        0x20: "V-L2 Max2",
        0x21: "V-L3 Max2",
        0x22: "V-L1 Min2",
        0x23: "V-L2 Min2",
        0x24: "V-L3 Min2",
        0x25: "V-L1 Max3",
        0x26: "V-L2 Max3",
        0x27: "V-L3 Max3",
        0x28: "V-L1 Min3",
        0x29: "V-L2 Min3",
        0x2A: "V-L3 Min3",
        0x2B: "V-L1 Max4",
        0x2C: "V-L2 Max4",
        0x2D: "V-L3 Max4",
        0x2E: "V-L1 Min4",
        0x2F: "V-L2 Min4",
        0x30: "V-L3 Min4",
        0x31: "V-L1 Max5",
        0x32: "V-L2 Max5",
        0x33: "V-L3 Max5",
        0x34: "V-L1 Min5",
        0x35: "V-L2 Min5",
        0x36: "V-L3 Min5",
        0x37: "V-Line Max",
        0x38: "V-Line Min",
        0x39: "I-ACDC L1",
        0x3A: "Unknown",
        0x3B: "I-ACDC L2",
        0x3C: "I-ACDC L3",
        0x3D: "I-RCD Step",
        0x3E: "I-RCD Max.",
        0x3F: "GRM Sync",
        0x40: "F-L1 Max1",
        0x41: "F-L2 Max1",
        0x42: "F-L3 Max1",
        0x43: "F-L1 Min1",
        0x44: "F-L2 Min1",
        0x45: "F-L3 Min1",
        0x46: "F-L1 Max2",
        0x47: "F-L2 Max2",
        0x48: "F-L3 Max2",
        0x49: "F-L1 Min2",
        0x4A: "F-L2 Min2",
        0x4B: "F-L3 Min2",
        0x4C: "F-L1 Max3",
        0x4D: "F-L2 Max3",
        0x4E: "F-L3 Max3",
        0x4F: "F-L1 Min3",
        0x50: "F-L2 Min3",
        0x51: "F-L3 Min3",
        0x52: "F-L1 Max4",
        0x53: "F-L2 Max4",
        0x54: "F-L3 Max4",
        0x55: "F-L1 Min4",
        0x56: "F-L2 Min4",
        0x57: "F-L3 Min4",
        0x58: "F-L1 Max5",
        0x59: "F-L2 Max5",
        0x5A: "F-L3 Max5",
        0x5B: "F-L1 Min5",
        0x5C: "F-L2 Min5",
        0x5D: "F-L3 Min5",
        0x5E: "VinP Max",
        0x5F: "VinM Max",
        0x60: "Islanding Trip1",
        0x61: "Vin Buck Max",
        0x62: "Islanding Trip2",
        0x63: "TZ RCD",
        0x64: "TZ L1",
        0x65: "TZ L2",
        0x66: "TZ L3",
        0x67: "TZ ITO",
        0x68: "TZ Misc",
        0x69: "Iac L1 Leg1 Max",
        0x6A: "Iac L2 Leg1 Max",
        0x6B: "Iac L3 Leg1 Max",
        0x6C: "Iac L1 Leg2 Max",
        0x6D: "Iac L2 Leg2 Max",
        0x6E: "Iac L3 Leg3 Max",
        0x6F: "Vsrg L1 Max \\ Breaker Disconnection",
        0x70: "Vsrg L2 Max",
        0x71: "Vsrg L3 Max",
        0x72: "Vdc Plus Max",
        0x73: "Vdc Minus Max",
        0x74: "Iswing Max",
        0x75: "Overtemp",
        0x76: "Undertemp",
        0x77: "Vref",
        0x78: "WatchDog Reset",
        0x79: "Int. Timing",
        0x7A: "Timing ISR2",
        0x7B: "Startup Error",
        0x7C: "ISR 16khz Error",
        0x7D: "Phase Error",
        0x7E: "Reserved3",
        0x7F: "Ircd Max.",
        0x80: "Vdc Balance Error",
        0x81: "VNN Error",
        0x82: "Low Power",
        0x83: "GRM",
        0x84: "Init",
        0x85: "Temp. Sensor fault",
        0x86: "Isolation",
        0x87: "Relay Test",
        0x88: "Offset Gain",
        0x89: "RCD Test",
        0x8A: "Switch",
        0x8B: "Test Iso Test",
        0x8C: "PLL Sync",
        0x8D: "Arc Detect Test",
        0x8E: "Arc Detection",
        0x8F: "Reserved Init4",
        0x90: "1 OK",
        0x91: "2 OK",
        0x92: "3 OK",
        0x93: "4 OK",
        0x94: "1 Dying",
        0x95: "2 Dying",
        0x96: "3 Dying",
        0x97: "4 Dying",
        0x98: "1 Dead",
        0x99: "2 Dead",
        0x9A: "3 Dead",
        0x9B: "4 Dead",
        0x9C: "Controller 12 Error",
        0x9D: "Controller 34 Error",
        0x9E: "Controller 3 Error",
        0x9F: "5 OK",
        0xA0: "6 OK",
        0xA1: "5 Dead",
        0xA2: "6 Dead",
        0xA3: "Tz Over current 1",
        0xA4: "Tz Over current 2",
        0xA5: "Tz Over current 3",
        0xA6: "Tz Over voltage cap1",
        0xA7: "Tz Over voltage cap2",
        0xA8: "Tz Over Voltage Cap3",
        0xA9: "Tz Over Current Rcd",
        0xAA: "Tz Over Voltage Bridge Cap",
        0xAB: "Tz Over Voltage Vin Buck",
        0xAC: "Tz Mngr Driver Dis",
        0xAD: "Tz Pwr Driver Dis",
        0xAE: "Tz OnOff Switch Dis",
        0xAF: "Tz RSD",
        0xB0: "Tz NC",
        0xB1: "Tz Global",
        0xB2: "Vf1 surge",
        0xB3: "Vf2 surge",
        0xB4: "Vf3 surge",
        0xB5: "DC/AC in-stage over voltage",
        0xB6: "DC/AC out-stage over voltage",
        0xB7: "DC/AC in-stage over voltage",
        0xB8: "DC/AC out-stage over voltage",
        0xB9: "DC/AC in-stage over voltage",
        0xBA: "DC/AC out-stage over voltage",
        0xBB: "Vin Min.",
        0xBC: "Power module voltage imbalance",
        0xBD: "Vfilter Unbalanced",
        0xBE: "Swing Rdiff Overheat",
        0xBF: "Swing Rcommon Overheat",
        0xC0: "Sync problem during grid connection",
        0xC1: "FPGA Parameter Error",
        0xC2: "Swing MaxVdiff Timeout",
        0xC3: "VgAvg-L1",
        0xC4: "VgAvg-L2",
        0xC5: "VgAvg-L3",
        0xC6: "Operating time Timeout",
        0xC7: "Rapid Shutdown",
        0xC8: "GB Event",
        0xC9: "Big Offset during calibration",
        0xCA: "MNGR Lock",
        0xCB: "Memory Overflow",
        0xCC: "Tz OV AC Surge",
        0xCD: "IL Boost Max",
        0xCE: "Vdc Boost Max",
        0xCF: "Arc Power Limit",
        0xD0: "Pairing Problem",
        0xD1: "Filter Cap Discharge Timeout",
        0xD2: "Tz Boost Over Current",
        0xD3: "Tz Boost Over Voltage",
        0xD4: "Thermal Derating",
        0xD5: "Params Corruption",
        0xD6: "Multiple Seq. GB",
        0xD7: "Swing ESR Est.",
        0xD8: "V-L1 Max 6 to 10",
        0xD9: "V-L2 Max 6 to 10",
        0xDA: "V-L3 Max 6 to 10",
        0xDB: "V-L1 Min 6 to 10",
        0xDC: "V-L2 Min 6 to 10",
        0xDD: "V-L3 Min 6 to 10",
        0xDE: "F-L1 Min 6 to 10",
        0xDF: "F-L2 Min 6 to 10",
        0xE0: "F-L3 Min 6 to 10",
        0xE1: "F-L1 Max 6 to 10",
        0xE2: "F-L2 Max 6 to 10",
        0xE3: "F-L3 Max 6 to 10",
        0xE4: "V-Line Max 2 to 10",
        0xE5: "V-Line Min 2 to 10",
        0xE6: "GB HW Event",
        0xE7: "Curb oscillation transition",
        0xE8: "VLite opt reset event",
        0xE9: "Vdc control stability issue",
        0xEA: "Portia ongrid prevention",
        0xEB: "V line to N 2 Max",
        0xEC: "V line to N 2 min",
        0xED: "Backup over-consumption",
        0xEE: "Backup over-consumption",
        0xEF: "Backup over-consumption",
        0xF0: "Vac too high for OL\\0ffgrid",
        0xF1: "9V battery is too low",
        0xF2: "HeartBeat FHB timeout",
        0xF3: "Switching to off-grid",
        0xF4: "Switching to on-grid",
        0xF5: "Emergency RSD triggered",
        0xF6: "AC cycle the inverter",
        0xF7: "Backup interface ATS error",
        0xF8: "PowerWall support activated",
        0xF9: "PowerWall support off",
        0xFB: "Pairing problem",
        0xFE: "AC Socket button pressed",
        0xFF: "AC Socket relay fault",
        0x100: "Arc detected",
        0x102: "ARC software exception",
        0x104: "Sense Connect Event on Power Optimizer",
        0x105: "Sense Connect Inverter Lock on Power Optimizer",
    },
    0x1C: {
        0x1: "EVSE Over Current (FPGA)",
        0x2: "EVSE Over Voltage (FPGA)",
        0x3: "EVSE GFCI (FPGA)",
        0x4: "EVSE Welded Relay",
        0x5: "EVSE Relay Not Closing",
        0x6: "EVSE Ground Disconnection From EV",
        0x7: "EVSE Over Temperature",
        0x8: "EVSE Over Current (M0)",
        0x9: "EVSE Over Voltage (M0)",
        0xA: "EVSE Under Voltage (M0)",
        0xB: "EVSE Shorted to PE",
        0xC: "Ventilation Error",
        0xD: "EVSE Pilot Voltage Limits",
        0xE: "EVSE Self-Test Retries",
        0xF: "EVSE Max Charging Retries",
        0x10: "EV Pilot Error (Diode)",
        0x11: "EV Pilot Error (Resistors)",
        0x12: "FPGA Init Failed",
        0x13: "Power-up Self-Test Failed",
        0x14: "EVSE GFCI (M0)",
        0x15: "EXT GFCI",
        0x16: "EV response time to current change is too long",
        0x50: "Power de-rating due to temperature",
        0x51: "Self-test: GFCI failed",
        0x52: "Self-test: relay failed",
        0x53: "Self-test: relay doesn't close",
    },
    0x1D: {
        0x0: "No event",
        0x1: "Wakeup",
        0x2: "User turned-off",
        0x3: "Start operation",
        0x4: "External reset",
        0x5: "TZ misc",
        0x6: "SW reset",
        0x7: "SysOpModeSet",
        0x8: "Operating time timeout",
        0x9: "CAN stop command",
        0xA: "CAN resume command",
        0xB: "Modbus initialization error",
        0xC: "CAN alarm no error code",
        0xD: "CAN alarm general",
        0xE: "CAN alarm over charge current",
        0xF: "CAN alarm over discharge current",
        0x10: "CAN alarm BMS internal error",
        0x11: "CAN alarm over voltage",
        0x12: "CAN alarm under voltage",
        0x13: "CAN alarm over temperature",
        0x14: "CAN alarm under temperature",
        0x15: "CAN alarm over temperature charge",
        0x16: "CAN alarm under temperature charge",
        0x17: "CAN alarm cell imbalance",
        0x18: "CAN warning no error code",
        0x19: "CAN warning general",
        0x1A: "CAN warning over charge current",
        0x1B: "CAN warning over discharge current",
        0x1C: "CAN warning BMS internal error",
        0x1D: "CAN warning over voltage",
        0x1E: "CAN warning under voltage",
        0x1F: "CAN warning over temperature",
        0x20: "CAN warning under temperature",
        0x21: "CAN warning over temperature charge",
        0x22: "CAN warning under temperature charge",
        0x23: "CAN warning cell imbalance",
        0x24: "Stop and kill battery command",
        0x25: "Communication board set battery command",
        0x26: "Communication board disable precharge command",
        0x27: "GRM general",
        0x28: "GRM battery zero current",
        0x29: "GRM battery SOC max",
        0x2A: "GRM battery SOC min",
        0x2B: "Accumulated energy input data out of range",
        0x2C: "Accumulated energy calculation reached max value",
        0x2D: "Started thermal derating",
        0x2E: "Fan internal test failed",
        0x2F: "Fan external test failed",
        0x30: "ZC Battery",
        0x34: "SubG Communication failure",
        0x64: "no error code",
        0x65: "no error code GRM",
        0x66: "TZ no error code",
        0x67: "FPGA parameter error",
        0x68: "TZ driver enable",
        0x69: "TZ LV over voltage",
        0x6A: "TZ LV under voltage",
        0x6B: "TZ HV over voltage",
        0x6C: "TZ HV under voltage",
        0x6D: "TZ Imax charge 2",
        0x6E: "TZ Imax discharge 2",
        0x6F: "TZ Imax charge 1",
        0x70: "TZ Imax discharge 1",
        0x71: "TZ battery",
        0x72: "TZ external enable",
        0x73: "Over temperature",
        0x74: "Temperature sensor fault",
        0x75: "Vref",
        0x76: "Int timing",
        0x77: "OpMode error",
        0x78: "12V enable turned-off",
        0x79: "Wait for go timeout",
        0x7A: "Wrong leg selection",
        0x7B: "Vdc max",
        0x7C: "Vdc min",
        0x7D: "Vbat max",
        0x7E: "Vbat min",
        0x7F: "Idc max",
        0x80: "Idc min",
        0x81: "Ibat max pre-charge",
        0x82: "Ibat min pre-charge",
        0x83: "Temperature high Line 1",
        0x84: "Temperature high Line 2",
        0x85: "CAN module error",
        0x86: "Battery TZ",
        0x87: "Vdc max for operation",
        0x88: "Heartbeat expired",
        0x89: "DV open terminal",
        0x8A: "DV short terminal",
        0x8B: "GRM Vdc max",
        0x8C: "GRM Vdc min",
        0x8D: "GRM Vbat max",
        0x8E: "GRM Vbat min",
        0x8F: "GRM max IHV charge",
        0x90: "GRM max IHV discharge",
        0x91: "GRM max ILV charge",
        0x92: "GRM max ILV discharge",
        0x93: "GRM 12V max",
        0x94: "GRM 12V min",
        0x95: "GRM 12Ven max",
        0x96: "GRM 12Ven min",
        0x97: "GRM 3.3V max",
        0x98: "GRM 3.3V min",
        0x99: "GRM 1.2V max",
        0x9A: "GRM 1.2V min",
        0x9B: "GRM telemetry Vbat max",
        0x9C: "GRM telemetry Vbat min",
        0x9D: "GRM telemetry max ILV charge",
        0x9E: "GRM telemetry max ILV discharge",
        0x9F: "Battery communication error",
        0xA0: "Battery error",
        0xA1: "No battery selected",
        0xA2: "Check operational conditions timeout",
        0xA3: "GRM Ibat max peak charge each leg",
        0xA4: "GRM Ibat max peak discharge each leg",
        0xA5: "Pre-charge process finished",
        0xB0: "Trip-zone secondary level protection BMS",
        0xB1: "Trip-zone AFE BMS",
        0xB2: "Trip-zone RSD out",
        0xB3: "Trip-zone IPK HV negative",
        0xB4: "Trip-zone POR status",
        0xB5: "SetVoltage over-voltage",
        0xB6: "SetVoltage under-voltage",
        0xB7: "SetVoltage error",
        0xB8: "GRC Ibat max",
        0xB9: "GRC Ibat min",
        0xBA: "GRC aux 12V max",
        0xBB: "GRC aux 12V min",
        0xBD: "GRC shunt correction",
    },
    0x26: {
        0x0: "No event",
        0x1: "External reset",
        0x2: "Params corruption",
        0x3: "Go on-grid",
        0x4: "Backup Interface state inconsistent",
        0x5: "Backup Interface state inconsistent",
        0x6: "Backup Interface state inconsistent",
        0x7: "Backup Interface thresholds error",
        0x8: "BUI state change - from Init to Backup",
        0x9: "BUI state change - from Init to On-Grid",
        0xA: "BUI state change - from Backup to On-Grid",
        0xB: "BUI state change - from On-Grid to Backup",
        0xC: "FHB Rapid Shutdown",
        0xD: "PLL out of sync",
        0xE: "PLL returned to sync",
        0xF: "Inverter doesn't lower AC voltage",
        0x10: "BUI wake up from reset",
        0x11: "Backup Interface low temperature",
        0x12: "Backup Interface high temperature",
        0x13: "BUI temperature return to allowed range",
        0x14: "Phase imbalance too high",
        0x15: "Generator above threshold without communication board command",
        0x16: "ATS and generator relays are connected simultaneously",
        0x17: "Dummy event generated by user",
        0x18: "Backup interface grid relay fault",
        0x1B: "Production halted - ATS / backup inconsistency",
        0x1C: "Production halted - ATS / VLL inconsistency",
        0x1E: "Inverter input voltage is out of range",
        0x21: "Backup interface grid relay fault",
        0x22: "Backup interface state inconsistent",
    },
    0x32: {
        0x8: "PID discharge",
        0x9: "PID no DC sensed",
        0xB: "PID output voltage don't rise",
        0xC: "PID over voltage",
        0xD: "PID under voltage",
        0xF: "Upgrade failed",
        0x10: "Left DC SPD triggered",
        0x11: "Center DC SPD triggered",
        0x12: "Right DC SPD triggered",
        0x13: "AC SPD triggered",
        0x14: "Left DC_P temperature rising",
        0x15: "Center DC_P temperature rising",
        0x16: "Right DC_P temperature rising",
        0x17: "Left DC_P temperature high",
        0x18: "Center DC_P temperature high",
        0x19: "Right DC_P temperature high",
        0x1D: "Left DC_N temperature rising",
        0x1E: "Center DC_N temperature rising",
        0x1F: "Right DC_N temperature rising",
        0x20: "Left DC_N temperature high",
        0x21: "Center DC_N temperature high",
        0x22: "Right DC_N temperature high",
        0x26: "AC L1 temperature rising",
        0x27: "AC L2 temperature rising",
        0x28: "AC L3 temperature rising",
        0x29: "AMB temperature rising",
        0x2A: "AC L1 temperature high",
        0x2B: "AC L2 temperature high",
        0x2C: "AC L3 temperature high",
        0x2D: "AMB temperature high",
        0x32: "Fan low RPM",
        0x33: "Fan high RPM",
        0x34: "Left unit DC+ temperature is very high",
        0x35: "Center unit DC+ temperature is very high",
        0x36: "Right unit DC+ temperature is very high",
        0x3A: "Left unit DC- temperature is very high",
        0x3B: "Center unit DC- temperature is very high",
        0x3C: "Right unit DC- temperature is very high",
        0x40: "AC L1 temperature is very high",
        0x41: "AC L2 temperature is very high",
        0x42: "AC L3 temperature is very high",
        0x4A: "Left unit locked due to DC+ over temperature",
        0x4B: "Center unit locked due to DC+ over temperature",
        0x4C: "Right unit locked due to DC+ over temperature",
        0x4D: "Left unit locked due to DC- over temperature",
        0x4E: "Center unit locked due to DC- over temperature",
        0x4F: "Right unit locked due to DC- over temperature",
        0x50: "Inverter locked due to AC L1 over temperature",
        0x51: "Inverter locked due to AC L2 over temperature",
        0x52: "Inverter locked due to AC L3 over temperature",
        0x54: "Watchdog",
        0x55: "Hard-fault",
        0x56: "Assert",
        0x57: "Stack overflow",
        0x58: "Heap overflow",
        0x5A: "Temperature DC_P left NTC disable",
        0x5B: "Temperature DC_P center NTC disable",
        0x5C: "Temperature DC_P right NTC disable",
        0x5D: "Temperature DC_N left NTC disable",
        0x5E: "Temperature DC_N center NTC disable",
        0x5F: "Temperature DC_N right NTC disable",
        0x60: "Temperature AC L1 NTC disable",
        0x61: "Temperature AC L2 NTC disable",
        0x62: "Temperature AC L3 NTC disable",
        0x63: "Temperature Ambient NTC disable",
    },
    0x33: {
        0x4: "Fpga Communication Error",
        0x5: "Dcmngr Init Error",
        0xC: "Dcmngr Communication Error",
        0x10: "Communication",
        0x11: "Unexpected Mode",
        0x14: "PID night error",
        0x17: "Main Capacitor Error",
        0x18: "Rapid Shutdown",
        0x19: "V-L1 Max1",
        0x1A: "V-L2 Max1",
        0x1B: "V-L3Max1",
        0x1C: "V-L1 Min1",
        0x1D: "V-L2 Min1",
        0x1E: "V-L3 Min1",
        0x1F: "V-L1 Max2",
        0x20: "V-L2 Max2",
        0x21: "V-L3 Max2",
        0x22: "V-L1 Min2",
        0x23: "V-L2 Min2",
        0x24: "V-L3 Min2",
        0x25: "V-Line Max_X000D_",
        0x26: "V-Line Min",
        0x27: "I-Acdc L1",
        0x28: "Unknown",
        0x29: "I-Acdc L2",
        0x2A: "I-Acdc L3",
        0x2B: "I-Rcd 1",
        0x2C: "I-Rcd 2",
        0x2E: "F-L1 Max",
        0x2F: "F-L2 Max",
        0x30: "F-L3 Max",
        0x31: "F-L1 Min",
        0x32: "F-L2 Min",
        0x33: "F-L3 Min",
        0x36: "Active Anti Islanding",
        0x37: "Vin Max",
        0x38: "Passive Anti Islanding",
        0x3F: "Iac L1 Max",
        0x40: "Iac L2 Max",
        0x41: "Iac L3 Max",
        0x42: "Vsrg L1 Max (Vac Voltage Spike)",
        0x43: "Vsrg L2 Max (Vac Voltage Spike)",
        0x44: "Vsrg L3 Max (Vac Voltage Spike)",
        0x45: "Vdc Plus Max (Vdc+ Voltage Spike)",
        0x46: "Vdc Minus Max (Vdc- Voltage Spike)",
        0x47: "Overtemp",
        0x48: "Undertemp",
        0x4B: "Fast Isr Timing",
        0x4C: "Igbt Phase Update Timing",
        0x4D: "Semi Fast Isr Timing",
        0x4E: "Sic Pwm Update Timing",
        0x4F: "SIC update Timing Error",
        0x52: "Vdc+/- Capacitors Banks Unbalanced",
        0x53: "Vnn Error",
        0x56: "Power Train Error",
        0x57: "Temp Sensor",
        0x58: "Isolation",
        0x59: "Relay Test",
        0x5A: "Ofset Gain",
        0x5B: "Rcd Test",
        0x5C: "Switch",
        0x5D: "Test Iso Test",
        0x5E: "Pllsync",
        0x63: "Vfilter Surge Line1 Legc Max (Vfilter Voltage Spike)",
        0x64: "Vfilter Surge Line2 Legc Max (Vfilter Voltage Spike)",
        0x65: "Vfilter Surge Line3 Legc Max (Vfilter Voltage Spike)",
        0x6C: "I Line 1 Leg C Difference",
        0x6D: "I Line 2 Leg C Difference",
        0x6E: "I Line 3 Leg C Difference",
        0x75: "Bank+ Over Voltage",
        0x76: "Bank- Over Voltage",
        0x7A: "L1-Over Current",
        0x7B: "L2-Over Current",
        0x7C: "L3-Over Current",
        0x81: "Rcd Over Current",
        0x83: "Global Fault",
        0x85: "The AC SPD is not functioning",
        0x86: "The DC SPD is not functioning",
        0x87: "F-L1 Max6To10",
        0x88: "F-L2 Max6To10",
        0x89: "F-L3 Max6To10",
        0x8A: "F-L1 Min6To10",
        0x8B: "F-L2 Min6To10",
        0x8C: "F-L3 Min6To10",
        0x8D: "V-L1 Max6To10",
        0x8E: "V-L2 Max6To10",
        0x8F: "V-L3Max6To10",
        0x90: "V-L1 Min6To10",
        0x91: "V-L2 Min6To10",
        0x92: "V-L3 Min6To10",
        0x93: "V-Line Max2To10",
        0x94: "V-Line Min2To10",
        0x9A: "Spd installation Ac error",
        0x9B: "Spd installation Dc error",
        0x9C: "Terminals Temperature Passed Critical Range",
        0xA5: "Multiple Seq Gb",
        0xB7: "Manager Startup Error",
        0xB8: "Pairing Error",
        0xC0: "No Active Grid Detect",
        0xC1: "Vfilter Discharge",
        0xC5: "Archs Exception",
        0xCF: "Cross Conduction Tz",
        0xE1: "Assert Fault",
        0xE2: "Stack Overflow Fault",
        0xE3: "Heap Overflow Fault",
    },
    0xF1: {
        0x1: "DCDC converter battery over-voltage",
        0x2: "DCDC converter battery over-current",
        0x3: "DCDC converter link over-voltage",
        0x4: "DCDC converter link over-current",
        0x5: "DCDC converter over-temperature",
        0x6: "DCDC converter BMS communication error",
        0x7: "DCDC converter inverter communication error",
        0x8: "DCDC converter link over-voltage CB open",
        0x9: "Over-voltage fault",
        0xA: "Under-voltage fault",
        0xB: "Deviation voltage fault",
        0xC: "Over-temperature fault",
        0xD: "Under-temperature fault",
        0xE: "Deviation temperature fault",
        0xF: "Over charge-current fault",
        0x10: "Over discharge-current fault",
        0x11: "Over charge-power limit fault",
        0x12: "Over discharge-power limit fault",
        0x13: "Battery Monitoring IC loss of communication fault",
        0x14: "Over-voltage fault2",
        0x15: "Under-voltage fault2",
        0x16: "Over-temperature fault2",
        0x17: "Under-temperature fault2",
        0x18: "Over charge-current fault2",
        0x19: "Over discharge-current fault2",
        0x1A: "Over charge-power limit fault2",
        0x1B: "Over discharge-power limit fault2",
        0x1C: "PCS loss of communication fault2",
        0x1D: "Battery Monitoring IC loss of communication fault2",
        0x1E: "BMS internal fault2",
        0x33: "Reverse polarity PV power charge DC",
        0x34: "Reverse polarity battery try to precharge",
    },
}
