blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/WillCodeForCats/solaredge-modbus-multi/discussions
    about: Please ask and answer questions here.
  - name: Home Assistant Community Support
    url: https://community.home-assistant.io/t/custom-component-solaredge-modbus-multi/
    about: Please ask and answer questions here.
