name: HACS Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
permissions: read-all
jobs:
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v5"
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"
