name: Python Code Quality Action

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: WillCodeForCats/python-lint-action@v1.0.1
        with:
          python-root-list: "custom_components/solaredge_modbus_multi"
          use-flake8: true
          use-black: true
          use-isort: true
